### ISSUE TITLE
CWordPadView::OnPageSetup() will crash if using unicode character set

### ISSUE THREAD

**Issue by Alan858** [pmachapman/WordPad#1]
if compiled with unicode character set, theApp.SelectPrinter(psd.hDevNames, psd.hDevMode); inside CWordPadView::OnPageSetup() crashes.

![image](https://user-images.githubusercontent.com/11062320/124505943-72b54700-dd7f-11eb-9641-d6cd7151444b.png)

Alan

**Comment by pmachapman** [comment]
Flagging for later follow up. @pmachapman

**Comment by pmachapman** [comment]
I an unable to recreate this issue when I set the character set to "Use Unicode Character Set".

Please re-open this ticket if it is still an issue after updating the the latest master branch, and provide additional details on how to recreate the issue, such as:
- The names of the printers installed
- The default printer
- The document you were trying to print preview
- Any other code or configuration changes made to the program
